spring:
   liquibase:
      change-log: classpath:db\liquibase-changelog.xml
   h2:
      console:
         enabled: false
   jpa:
      hibernate:
         ddl-auto: none
logging:
   level:
      root: INFO
      
fortest: HELLO
         