spring:
   h2:
      console:
         enabled: true
   jpa:
      hibernate:
         ddl-auto: none
   liquibase:
      change-log: classpath:db/liquibase-changelog.xml
   thymeleaf: cache=false
welcome:
   message: Hello Thymeleaf
error:
   message: First Name & Last Name is required!