spring:
   rabbitmq:
      addresses: ${RABBITMQ_ADDRESS:localhost}                 
                                  
   h2:
      console:
         enabled: true
#   datasource:
#      driverClassName: ${DB_DRIVER:org.h2.Driver}
#      url: ${DB_URL:jdbc:h2:mem:library-db}
#      user: ${DB_USER:sa}

   jpa:
      hibernate:
         ddl-auto: none
   liquibase:
      change-log: classpath:db/liquibase-changelog.xml
   thymeleaf:
      cache: false
   resources:
      add-mappings: true
   data:
      rest:
         basePath: /datarest
server:
   error:
      include-stacktrace: always
management:
   endpoints:
      web:
         exposure:
            include: health, logfile, metrics
   endpoint:
      health:
         show-details: always
logging:
   file: log.txt