spring:
   h2:
      console:
         enabled: true
   jpa:
      hibernate:
         ddl-auto: none
   liquibase:
      change-log: classpath:db/liquibase-changelog.xml
   thymeleaf: cache=false
   resources:
      add-mappings: true
server:
   error:
      include-stacktrace: always