spring:

  rabbitmq:
    addresses: rabbitmq
    
  datasource:
    driverClassName: ${DB_DRIVER}      
    url: ${DB_URL}
    user: ${DB_USER}
                                   
  jpa:
      hibernate:
         ddl-auto: none
  liquibase:
      change-log: classpath:db/liquibase-changelog.xml

management:
  endpoints:
    web:
      exposure:
        include: health, info, activitystat
  endpoint:
    health:
      show-details: always

logging:
  file: log.txt