spring:
  port: 8082
 
  rabbitmq:
    addresses: localhost

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:192.168.99.100:1521/activity-processor-db
    user: sa                                
   
  jpa:
      hibernate:
         ddl-auto: none
  liquibase:
      change-log: classpath:db/liquibase-changelog.xml

management:
  endpoints:
    web:
      exposure:
        include: health, info, activity-stat
  endpoint:
    health:
      show-details: always