DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID INT  NOT NULL AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255),  BIRTHDATE DATE);


DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, DESCRIPTION VARCHAR(255));

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
				BOOKNAME VARCHAR(255),   
				AUTHORID INT, FOREIGN KEY (AUTHORID) REFERENCES AUTHOR(ID), 
				GENREID INT, FOREIGN KEY (GENREID) REFERENCES GENRE(ID));

