DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID INT  NOT NULL AUTO_INCREMENT, NAME VARCHAR(255),  BIRTHDATE DATE);

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(ID INT NOT NULL AUTO_INCREMENT, BOOKNAME VARCHAR(255),  AUTHORID INT, GENREID INT);

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(ID INT NOT NULL AUTO_INCREMENT, DESCRIPTION VARCHAR(255));