DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID INT PRIMARY KEY, NAME VARCHAR(255),  BIRTHDATE DATE);

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(ID INT PRIMARY KEY, TITTLE VARCHAR(255),  AUTHORID INT, GENREID INT);