spring:
   h2:
      console:
         enabled: true
   jpa:
      hibernate:
         ddl-auto: none
   liquibase:
      change-log: classpath:db/liquibase-changelog.xml
   thymeleaf: 
      cache: false
   resources:
      add-mappings: true
      
   data:
      rest:
        basePath: /datarest
      
server:
   error:
      include-stacktrace: always
                        
management:
  endpoints:
    web:
      exposure:
        include: health, logfile, metrics
  endpoint:
    health:
      show-details: always
      
logging:
  file: log.txt    